import {Dimensions, StyleSheet} from 'react-native';
import {COLORS, FONTS, SIZES} from '../../constants/theme';

const windowWidth = Dimensions.get('screen').width;
const windowHeight = Dimensions.get('screen').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  appBar: {
    flex: 0.1,
    width: windowWidth,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnReload: {
    backgroundColor: COLORS.primary,
    width: 80,
    height: 30,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 0.9,
    width: windowWidth,
  },
  title: {
    fontFamily: FONTS.Bold,
    fontSize: SIZES.xLarge,
    color: COLORS.black,
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  description: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.medium,
    color: COLORS.gray,
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  btnView: {
    width: windowWidth,
    justifyContent: 'center',
    alignItems: 'center',
  },
  browserBtn: {
    width: windowWidth * 0.8,
    height: windowWidth * 0.7,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: windowWidth * 0.25,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderStyle: 'dashed',
    borderColor: COLORS.black,
    borderWidth: 2,
    marginVertical: 40,
  },
  btnText: {
    marginTop: 10,
    fontFamily: FONTS.Regular,
    fontSize: SIZES.medium,
    color: COLORS.black,
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  bottomView: {
    width: windowWidth,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 20,
  },
  convertBtn: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.07,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  textBtn: {
    fontFamily: 'semiBold',
    fontSize: SIZES.medium + 4,
    color: 'white',
  },
  iconStyle: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  iconReloadStyle: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  imageView: {
    paddingHorizontal: 10,
    width: windowWidth * 0.9,
    height: windowHeight * 0.1,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    borderRadius: 8,
    borderColor: COLORS.primary,
    borderWidth: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  titleImage: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.large,
    COLORS: COLORS.black,
  },
  sizeImage: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.medium,
    COLORS: COLORS.black,
  },
  imagePDFView: {
    width: 50,
    height: 70,
    borderRadius: 8,
    borderColor: COLORS.primary,
    borderWidth: 2,
    marginRight: 20,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageItem: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  textItem: {
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    height: 50,
  },
  resultView: {
    width: windowWidth,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  resultImageView: {
    width: 200,
    height: 200,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pdf96Image: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  nameText: {
    marginVertical: 20,
    fontFamily: FONTS.Regular,
    fontSize: SIZES.large,
    color: COLORS.black,
  },
  modalView: {
    width: windowWidth,
    height: windowHeight,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: COLORS.black,
    opacity: 0.4,
  },
  modal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.25,
    backgroundColor: COLORS.white,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
  },
  modalStatusContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.15,
    backgroundColor: COLORS.white,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
  },
  topStatusView: {
    flex: 0.8,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e1e1',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.large,
    color: COLORS.black,
  },
  topView: {
    flex: 0.3,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e1e1',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnOK: {
    flex: 0.5,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleText: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.large,
    color: COLORS.black,
  },
  textBtnModal: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.large,
  },
  centerView: {
    paddingHorizontal: 20,
    flex: 0.5,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e1e1',
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  bottomViewModal: {
    flex: 0.2,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  input: {
    marginTop: 10,
    paddingLeft: 20,
    width: '100%',
    height: 40,
    borderWidth: 1,
    borderRadius: 2,
    padding: 10,
  },
  cancelBtn: {
    width: '50%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#e1e1e1',
  },
  inputView: {
    width: '80%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  inputStyle: {
    width: 50,
    height: 50,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: COLORS.gray,
    paddingLeft: 10,
    fontSize: SIZES.medium,
    fontFamily: FONTS.Medium,
    color: COLORS.black,
  },
  splitText: {
    fontSize: SIZES.large,
    fontFamily: FONTS.Medium,
    color: COLORS.black,
  },
});
