import {Dimensions, StyleSheet} from 'react-native';
import {COLORS, FONTS, SIZES} from '../../constants/theme';

const windowWidth = Dimensions.get('screen').width;
const windowHeight = Dimensions.get('screen').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    width: windowWidth,
  },
  appBar: {
    height: windowHeight * 0.06,
    width: windowWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleText: {
    fontFamily: FONTS.Bold,
    fontSize: SIZES.xLarge,
    color: COLORS.black,
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  descriptionText: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.medium,
    color: COLORS.gray,
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  centerView: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    width: windowWidth,
    height: windowHeight * 0.75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyFolderImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  allowBtn: {
    marginVertical: 10,
    width: windowWidth * 0.5,
    height: windowHeight * 0.05,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBtn: {
    fontFamily: FONTS.SemiBold,
    fontSize: SIZES.medium,
    color: 'white',
  },
  modalView: {
    width: windowWidth,
    height: windowHeight,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: COLORS.black,
    opacity: 0.4,
  },
  modalContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topView: {
    width: windowWidth * 0.95,
    height: windowHeight * 0.32,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: 16,
    flex: 1,
  },
  descriptionView: {
    width: '90%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 10,
    flex: 0.4,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e1e1',
  },
  iconCloseStyle: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  cancelBtn: {
    marginTop: 10,
    marginBottom: 20,
    width: windowWidth * 0.95,
    height: windowHeight * 0.07,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBtn: {
    flex: 0.2,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    width: '90%',
    borderBottomColor: '#e1e1e1',
  },
  btnText: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.xLarge,
    color: COLORS.black,
  },
  btnDeleteText: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.xLarge,
    color: COLORS.primary,
  },
  pdfImages: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
  },
  pdfBorder: {
    width: 60,
    height: 70,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderColor: COLORS.primary,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  textView: {
    marginLeft: 10,
    justifyContent: 'space-between',
    height: 60,
  },
  titleItem: {
    fontFamily: FONTS.SemiBold,
    fontSize: SIZES.medium + 2,
    color: COLORS.black,
  },
  timeItem: {
    fontFamily: FONTS.Regular,
    fontSize: SIZES.small + 2,
    color: COLORS.black,
  },
});
